### ISSUE TITLE
Build the XML parsing

### ISSUE THREAD

**Issue by Ronin11** [UnknownJoe796/2Risky#3]
We need to build the XML to read in and parse for the game state creation. I'll build that XML and the code to read and parse it.

**Comment by Ronin11** [comment]
The XML is build and uploaded to the Nate_work branch. Once the Game state code is completed, we can finalize the XML parsing code. ATM the code simply prints out the file in a tabbed form of the XML format.

**Comment by juyoung101** [comment]
Pull request #19 takes care of this.
